// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx7EmtYog9lj8zOXrSCF-dVQtLefn5r_c',
    appId: '1:927974955707:web:16731c9f14b20f8274279e',
    messagingSenderId: '927974955707',
    projectId: 'adda2-f00bb',
    authDomain: 'adda2-f00bb.firebaseapp.com',
    storageBucket: 'adda2-f00bb.firebasestorage.app',
    measurementId: 'G-PKZRYYVH5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPxGbXU3FvwhA53DcZYZMX9E3tzHPRE4',
    appId: '1:927974955707:android:f061a8e18a3947d474279e',
    messagingSenderId: '927974955707',
    projectId: 'adda2-f00bb',
    storageBucket: 'adda2-f00bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlNj7vQnXmI5oUHz6JST699O9e7NLysZw',
    appId: '1:927974955707:ios:cc05f7a8634f8a0d74279e',
    messagingSenderId: '927974955707',
    projectId: 'adda2-f00bb',
    storageBucket: 'adda2-f00bb.firebasestorage.app',
    androidClientId: '927974955707-itm4m30aoedu6q02l1fnlvkrri3maa1h.apps.googleusercontent.com',
    iosClientId: '927974955707-kvgldjkl8cmnmquqlkj0q1irpkiah209.apps.googleusercontent.com',
    iosBundleId: 'com.example.adda2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlNj7vQnXmI5oUHz6JST699O9e7NLysZw',
    appId: '1:927974955707:ios:cc05f7a8634f8a0d74279e',
    messagingSenderId: '927974955707',
    projectId: 'adda2-f00bb',
    storageBucket: 'adda2-f00bb.firebasestorage.app',
    androidClientId: '927974955707-itm4m30aoedu6q02l1fnlvkrri3maa1h.apps.googleusercontent.com',
    iosClientId: '927974955707-kvgldjkl8cmnmquqlkj0q1irpkiah209.apps.googleusercontent.com',
    iosBundleId: 'com.example.adda2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx7EmtYog9lj8zOXrSCF-dVQtLefn5r_c',
    appId: '1:927974955707:web:296d94bca84015e774279e',
    messagingSenderId: '927974955707',
    projectId: 'adda2-f00bb',
    authDomain: 'adda2-f00bb.firebaseapp.com',
    storageBucket: 'adda2-f00bb.firebasestorage.app',
    measurementId: 'G-L97TNQCRCE',
  );
}
