// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT1qAU-EOrVTEBPW1iL1q8kknjghtZM90',
    appId: '1:153080448097:web:f0f16faeb7ad45225bd620',
    messagingSenderId: '153080448097',
    projectId: 'adda-aa69b',
    authDomain: 'adda-aa69b.firebaseapp.com',
    databaseURL: 'https://adda-aa69b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adda-aa69b.firebasestorage.app',
    measurementId: 'G-YNWPWJPSH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT17kFsZnMAg33x2TjrbYkm4zEx7569ZA',
    appId: '1:153080448097:android:2afa117c820c188e5bd620',
    messagingSenderId: '153080448097',
    projectId: 'adda-aa69b',
    databaseURL: 'https://adda-aa69b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adda-aa69b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcCWfE6iQf5HVt0UFVHZ7xyx2F_mwil3c',
    appId: '1:153080448097:ios:82b7c323254c3d5f5bd620',
    messagingSenderId: '153080448097',
    projectId: 'adda-aa69b',
    databaseURL: 'https://adda-aa69b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adda-aa69b.firebasestorage.app',
    androidClientId: '153080448097-hdc11sp8og81igrl8n1cfijgl850iehv.apps.googleusercontent.com',
    iosClientId: '153080448097-p94fjqnqpi5hl1pda9sq9sa7mgso5jb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcCWfE6iQf5HVt0UFVHZ7xyx2F_mwil3c',
    appId: '1:153080448097:ios:82b7c323254c3d5f5bd620',
    messagingSenderId: '153080448097',
    projectId: 'adda-aa69b',
    databaseURL: 'https://adda-aa69b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adda-aa69b.firebasestorage.app',
    androidClientId: '153080448097-hdc11sp8og81igrl8n1cfijgl850iehv.apps.googleusercontent.com',
    iosClientId: '153080448097-p94fjqnqpi5hl1pda9sq9sa7mgso5jb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT1qAU-EOrVTEBPW1iL1q8kknjghtZM90',
    appId: '1:153080448097:web:014d0f593011afbd5bd620',
    messagingSenderId: '153080448097',
    projectId: 'adda-aa69b',
    authDomain: 'adda-aa69b.firebaseapp.com',
    databaseURL: 'https://adda-aa69b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adda-aa69b.firebasestorage.app',
    measurementId: 'G-6EB64MJX3C',
  );
}
